server:
  port: 8078
  tomcat:
    threads:
      max: 300
#
####################################################################################################
############################################# ChrylConfigProperty 相关变量配置 ######################
####################################################################################################
chryl:
  ######################################################################## XCC
  #  XSwitch config
  nats-url: nats://hy:h8klu6bRwW@nats.xswitch.cn:4222
  xctrl-subject: cn.xswitch.ctrl.event.detected_speech
  xnode-subject-prefix: cn.xswitch.node
  # no break 是否打断放音, true 不可打断
  no-break: false
  # XML数据需要自己处理, JSON数据XSwitch已深度解析, true开启自助解析
  handle-engine-data: true
  # DTMF 输入超时(多位按键输入)
  dtmf-no-input-timeout: 30
  # DTMF 输入超时(少位按键输入)
  dtmf-chryl-no-input-timeout: 5
  # DTMF 位间超时
  digit-timeout: 13
  # speech 未检测到语音超时(秒)
  speech-no-input-timeout: 10
  # 语音超时，即如果对方讲话一直不停超时，最大只能设置成6000ms，默认为6000ms。
  speech-timeout: 6
  # 语音最大超时，和参数speech_timeout作用相同，如果max_speech_timeout的值大于speech_timeout，则以max_speech_timeout为主，用于一些特殊场景的语音时长设置。
  max-speech-timeout: 8
  #
  # 若有多台XSwitch,再开启,true开启
  cluster: true
  #配置多节点
  nats-list:
    - node: 10.194.31.201
      nats: nats://10.194.31.200:4222
    - node: 10.194.31.203
      nats: nats://10.194.31.202:4222
  ######################################################################## XCC
  ######################################################################## NGD
  #  ngd  query url
  ngd-core-query-url: http://10.100.104.20:8303/api/v2/core/query
  #  ngd bot token
  ngd-bot-token: NGD 218bbd82-2336-4561-8858-d3cca6e630ac
  # convert solved :ngd存在solved=false，是否选择处理，true开启
  convert-solved: true
  ######################################################################## NGD
  ######################################################################## ASR
  #  asr engine
  asr-engine: unimrcp:asr
  ######################################################################## ASR
  ######################################################################## TTS
  #  tts engine
  tts-engine: unimrcp:tts
  #  Voice-Name
  tts-voice: yifei
  # 是否开启多tts voice规则,true开启
  tts-voice-rule: true
  # voice list
  tts-voice-list:
    - 'yifei'
    - 'chongchong'
  # TTS 语速 格式：	[s*]	(*=0~10) ,默认语速值为5
  xtts-s: s4
  ######################################################################## TTS
  ######################################################################## WebHook
  # webhook url
  webhook-url: http://10.100.104.30:8090/gddw/electric
  ######################################################################## WebHook
  ######################################################################## PMS
  # pms 营销地址
  pms-url: http://10.100.175.10:8080/PMS_WS/services
######################################################################## PMS
######################################################################## LOG
# log path
logback:
  path: /home/app/chryl/logs/event/
######################################################################## LOG
####################################################################################################
############################################# ChrylConfigProperty 相关变量配置 ######################
####################################################################################################